
package co.gov.banrep.kepiaa.menu.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "AdministradorMenuException", targetNamespace = "http://banrep.gov.co/s3")
public class AdministradorMenuException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private AdministradorMenuException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public AdministradorMenuException_Exception(String message, AdministradorMenuException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public AdministradorMenuException_Exception(String message, AdministradorMenuException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: co.gov.banrep.kepiaa.menu.webservice.AdministradorMenuException
     */
    public AdministradorMenuException getFaultInfo() {
        return faultInfo;
    }

}
