
package co.gov.banrep.kepiaa.menu.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AdministradorMenuWS", targetNamespace = "http://banrep.gov.co/s3")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AdministradorMenuWS {


    /**
     * 
     * @param data
     * @return
     *     returns co.gov.banrep.kepiaa.menu.webservice.RespuestaConsultarMenuPerfil
     * @throws AdministradorMenuException_Exception
     */
    @WebMethod(action = "consultarMenuPerfil")
    @WebResult(targetNamespace = "http://banrep.gov.co/s3")
    @RequestWrapper(localName = "consultarMenuPerfil", targetNamespace = "http://banrep.gov.co/s3", className = "co.gov.banrep.kepiaa.menu.webservice.ConsultarMenuPerfil")
    @ResponseWrapper(localName = "consultarMenuPerfilResponse", targetNamespace = "http://banrep.gov.co/s3", className = "co.gov.banrep.kepiaa.menu.webservice.ConsultarMenuPerfilResponse")
    public RespuestaConsultarMenuPerfil consultarMenuPerfil(
        @WebParam(name = "data", targetNamespace = "")
        PeticionConsultarMenuPerfil data)
        throws AdministradorMenuException_Exception
    ;

}
